Blog app - Add forms
DevaWinner/blog-app pull request #8
Opened 2023-10-14 23:13 UTC by DevaWinner

In this PR I made the following changes:

- Created a method called current_user in ApplicationController
- Created a Post on behalf of the current_user
- Created a comment on behalf of the current_user
- Function to allow Users to add likes to Posts.

2023-10-14 23:33 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @DevaWinner,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [ ] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-14 23:33 UTC, Omar-Muhamad commented on app/controllers/posts_controller.rb
> +  end
- [ ] [Optional] Please make `post_params` a private method because this is the correct way of making strong params.

2023-10-14 23:33 UTC, Omar-Muhamad commented on app/controllers/comments_controller.rb
> +    @comment = @post.comments.new(comment_params.merge(author: @user))
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/forms_project_v1_1.md#:~:text=Create%20a%20comment%20on%20behalf%20of%20the%20current_user), Please create a comment on behalf of the current_user (use the method that you created in your ApplicationController).

[Hint] You can make it like that:

```ruby
def create
    @comment = @current_user.comments.new(params)

    # The rest of the code here
```

2023-10-28 11:47 UTC, KayLemba approved these changes
# STATUS: APPROVED 🟢 👏

Hello @DevaWinner 
Your project is complete! There is nothing else to say other than... it's time to merge it  .
Congratulations! 🎉 Keep up the Awesome work 🥂 Keep Rocking 🥇

HIGHLIGHTS:

 Your repo is professional 😎 
Descriptive P.R 💯 Professional README file
App runs as intended

Now you can merge this branch and move on 🥇
Happy Coding cheers 🥇 💯

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using 

2023-11-04 20:52 UTC, merged